<?php

abstract class Block
{
    abstract function render();
}

class TextBlock extends Block
{
    public function render()
    {
        require_once("views/Text.html");
    }
}
class ImageBlock extends Block
{
    public function render()
    {
        require_once("views/Image.html");
    }
}
class ButtonBlock extends Block
{
    public function render()
    {
        require_once("views/Button.html");
    }
}

abstract class CompositeBlock extends Block
{
    protected $obj = array();

    public function addObj(Block $block)
    {
        array_push ($this -> obj , $block);
    }

    public function renderComposition()
    {
        foreach($this -> obj as $item){
            echo $item->render();
        }
    }

    public function getComposite()
    {
        return $this;
    }
}

class CreateBlock extends CompositeBlock
{
    public function addObj(Block $block)
    {
        parent::addObj($block); // TODO: Change the autogenerated stub
    }
    public function renderComposition()
    {
        parent::renderComposition(); // TODO: Change the autogenerated stub
    }
    public function render()
    {
        // TODO: Implement render() method.
    }
}


$block = new CreateBlock();
$block -> addObj(new TextBlock);
$block -> addObj(new ImageBlock);
$block -> renderComposition();